# Export daily precipitation in mm

In [10]:
%matplotlib inline
import xarray as xr
import pandas as pd
import numpy as np


## Import dataset

In [11]:
df0 = xr.open_dataset("pr_day_GFDL-ESM2M_historical_r1i1p1_EWEMBI_landonly_19710101-19801231_sp_exp.nc4")
df1 = xr.open_dataset("pr_day_GFDL-ESM2M_historical_r1i1p1_EWEMBI_landonly_19810101-19901231_sp_exp.nc4")
df2 = xr.open_dataset("pr_day_GFDL-ESM2M_historical_r1i1p1_EWEMBI_landonly_19910101-20001231_sp_exp.nc4")
df3 = xr.open_dataset("pr_day_GFDL-ESM2M_historical_r1i1p1_EWEMBI_landonly_20010101-20051231_sp_exp.nc4")
df=[df0, df1, df2, df3]
df0.variables

Frozen(OrderedDict([('lon', <xarray.IndexVariable 'lon' (lon: 38)>
array([-57.75, -57.25, -56.75, -56.25, -55.75, -55.25, -54.75, -54.25, -53.75,
       -53.25, -52.75, -52.25, -51.75, -51.25, -50.75, -50.25, -49.75, -49.25,
       -48.75, -48.25, -47.75, -47.25, -46.75, -46.25, -45.75, -45.25, -44.75,
       -44.25, -43.75, -43.25, -42.75, -42.25, -41.75, -41.25, -40.75, -40.25,
       -39.75, -39.25])
Attributes:
    standard_name:  longitude
    long_name:      longitude
    units:          degrees_east
    axis:           X), ('lat', <xarray.IndexVariable 'lat' (lat: 26)>
array([-16.25, -16.75, -17.25, -17.75, -18.25, -18.75, -19.25, -19.75, -20.25,
       -20.75, -21.25, -21.75, -22.25, -22.75, -23.25, -23.75, -24.25, -24.75,
       -25.25, -25.75, -26.25, -26.75, -27.25, -27.75, -28.25, -28.75])
Attributes:
    standard_name:  latitude
    long_name:      latitude
    units:          degrees_north
    axis:           Y), ('time', <xarray.IndexVariable 'time' (time: 3653)>
array([

## extract

In [12]:
points=[]
for i in [-22.25, -22.75, -23.25]:
    for j in [-47.75, -47.25, -46.75, -46.25]:
        points.append([i,j])

In [13]:
dec=[]
for coords in points:
    for ano in range(0,4):
        dec.append(pd.DataFrame((df[ano].
                                 sel(lon = coords[1], lat = coords[0])["pr"]).data*3600*24 ,
                                index = df[ano].sel(lon = coords[1], lat = coords[0]).time).round())

In [14]:
grid = []
for i in range(0,len(dec),4):
    grid.append(pd.concat(dec.copy()[i:i+4]))

## Export 

In [15]:
#já exporta no formato usado pelo SWAT
for i in range(len(grid)):
    grid[i].to_csv(path_or_buf= "pr_grid"+str(i)+".txt", index = False, header = ["19710101"])

# TESTS


In [130]:
dec=[]
for coords in points:
    for ano in range(0,4):
        dec.append(pd.Series((df[ano].
                                 sel(lon = coords[1], lat = coords[0])["tasmax"]*3600*24/1000000).data))

In [136]:
grid0 = pd.concat(dec.copy()[0:4])
grid1 = pd.concat(dec.copy()[4:8])
grid2 = pd.concat(dec.copy()[8:12])
grid3 = pd.concat(dec.copy()[12:16])
grid4 = pd.concat(dec.copy()[16:20])
grid5 = pd.concat(dec.copy()[20:24])
grid6 = pd.concat(dec.copy()[24:28])
grid7 = pd.concat(dec.copy()[28:32])
grid8 = pd.concat(dec.copy()[32:36])
grid9 = pd.concat(dec.copy()[36:40])
grid10 = pd.concat(dec.copy()[40:44])
grid11 = pd.concat(dec.copy()[44:48])
grid = [grid0, grid1,grid2,grid3,grid4,grid5,grid6,grid7,grid8, grid9,grid10,grid11]

In [137]:
for i in range(len(grid)):
    grid[i].to_csv()

In [142]:
grid0.values[:]

array([ 18.979532,  16.227549,  17.721742, ...,  23.815862,  26.677926,
        20.0995  ])

In [6]:
from collections import defaultdict
m=defaultdict(list)
m

defaultdict(list, {})

In [7]:

for i in range(5):
    len(m[i])


In [62]:
df

0
time                 
2001-01-01  17.398046
2001-01-02   9.592203
2001-01-03  22.353700
2001-01-04  22.154392
2001-01-05  16.385834
2001-01-06  17.172856
2001-01-07  22.613202
2001-01-08  25.254366
2001-01-09  19.349718
2001-01-10  21.424792
2001-01-11  19.412968
2001-01-12  18.959710
2001-01-13  21.009154
2001-01-14  22.913288
2001-01-15   8.162275
2001-01-16   3.386454
2001-01-17   6.262746
2001-01-18  16.313952
2001-01-19  19.109040
2001-01-20  17.795436
2001-01-21  27.443296
2001-01-22  28.304720
2001-01-23  28.074536
2001-01-24  20.421212
2001-01-25  21.445338
2001-01-26  26.561100
2001-01-27  26.586880
2001-01-28  24.937510
2001-01-29  25.790898
2001-01-30  20.658620
...               ...
2005-12-02  18.346836
2005-12-03  22.696220
2005-12-04  27.508312
2005-12-05  28.594992
2005-12-06  29.180488
2005-12-07  28.865412
2005-12-08  28.428462
2005-12-09  18.563036
2005-12-10  26.886416
2005-12-11  28.667610
2005-12-12  28.925874
2005-12-13  18.252036
2005-12-14  12.999336
2005-12-15  21.704466
2005-12-16   9.228031
2005-12-17   8.623416
2005-12-18   9.832341
2005-12-19   4.228313
2005-12-20  14.259243
2005-12-21  25.742284
2005-12-22  21.666608
2005-12-23  24.188980
2005-12-24  18.831882
2005-12-25  25.040788
2005-12-26  13.632262
2005-12-27  21.697468
2005-12-28  16.417594
2005-12-29  19.213328
2005-12-30  25.001082
2005-12-31  10.734250

[1826 rows x 1 columns]

In [96]:
grid0 = pd.concat(dec.copy()[0:4])
grid1 = pd.concat(dec.copy()[4:8])
grid2 = pd.concat(dec.copy()[8:12])
grid3 = pd.concat(dec.copy()[12:16])
grid4 = pd.concat(dec.copy()[16:20])
grid5 = pd.concat(dec.copy()[20:24])
grid6 = pd.concat(dec.copy()[24:28])
grid7 = pd.concat(dec.copy()[28:32])
grid8 = pd.concat(dec.copy()[32:36])
grid9 = pd.concat(dec.copy()[36:40])
grid10 = pd.concat(dec.copy()[40:44])
grid11 = pd.concat(dec.copy()[44:48])

In [98]:
grid11

0
time                 
1971-01-01  19.002560
1971-01-02  17.186056
1971-01-03  17.786564
1971-01-04  11.738238
1971-01-05   7.787505
1971-01-06   3.674282
1971-01-07   5.969739
1971-01-08   5.800960
1971-01-09  14.151036
1971-01-10   9.837920
1971-01-11   4.224078
1971-01-12  10.482675
1971-01-13  10.946004
1971-01-14   5.890720
1971-01-15  20.497228
1971-01-16  25.724556
1971-01-17  23.415430
1971-01-18  19.713688
1971-01-19  16.382020
1971-01-20  21.160024
1971-01-21  18.367818
1971-01-22  13.351270
1971-01-23  14.098594
1971-01-24  13.101087
1971-01-25   9.639831
1971-01-26  10.572973
1971-01-27   9.671228
1971-01-28  23.688452
1971-01-29  22.190402
1971-01-30  14.478688
...               ...
2005-12-02  18.346836
2005-12-03  22.696220
2005-12-04  27.508312
2005-12-05  28.594992
2005-12-06  29.180488
2005-12-07  28.865412
2005-12-08  28.428462
2005-12-09  18.563036
2005-12-10  26.886416
2005-12-11  28.667610
2005-12-12  28.925874
2005-12-13  18.252036
2005-12-14  12.999336
2005-12-15  21.704466
2005-12-16   9.228031
2005-12-17   8.623416
2005-12-18   9.832341
2005-12-19   4.228313
2005-12-20  14.259243
2005-12-21  25.742284
2005-12-22  21.666608
2005-12-23  24.188980
2005-12-24  18.831882
2005-12-25  25.040788
2005-12-26  13.632262
2005-12-27  21.697468
2005-12-28  16.417594
2005-12-29  19.213328
2005-12-30  25.001082
2005-12-31  10.734250

[12784 rows x 1 columns]